### ISSUE TITLE
failed to setup after update to 2024.9.1

### ISSUE THREAD

**Issue by Rvh91** [MarcoGos/kleenex_pollenradar#13]
After updating to HA 2024.9.1 (from 2024.8.3) I get the following error in the logs:

Setup failed for custom integration 'kleenex_pollenradar': Requirements for kleenex_pollenradar not found: ['beautifulsoup4==4.10.0'].

To be honest I'm not entirely sure where to start debugging here, as I don't know what beautifulsoup4 is. Can someone help me fix this?

**Comment by MarcoGos** [comment]
@Rvh91 , I've no idea what caused this issue. I'm on 2024.9.1 myself and didn't have it. Maybe try to remove the integration and reinstall it again. That will probably fix the issue.

**Comment by Rvh91** [comment]
Unfortunately I get the same error again. (integration could not be loaded). I have also tried to restart Home Assistant as suggested but no luck.

**Comment by MarcoGos** [comment]
@Rvh91 I tried to install the Pollen Radar integration on a freshly installed home assistant instance and had no problems. It looks like the needed beautifulsoap4 py library cannot automatically be loaded/retrieved on your end. I've no idea to fix it.

**Comment by Rvh91** [comment]
I think i accidentally bricked my system by updating the proxmox host while the system was running or something. I created a new HOAS vm and was able to restore a backup. now everything is working fine. Thanks for confirming you could install it on a fresh HA instance! It made me look elsewhere for the issue.

**Comment by MarcoGos** [comment]
You're welcome
