### ISSUE TITLE
Home Assistant 2024.11.0b1 breaks integration

### ISSUE THREAD

**Issue by EDelsman** [MarcoGos/kleenex_pollenradar#14]
Exception:

Logger: custom_components.kleenex_pollenradar
Bron: custom_components/kleenex_pollenradar/coordinator.py:44
integratie: Kleenex Pollen Radar (documentatie, problemen)
Eerst voorgekomen: 22:06:18 (40 gebeurtenissen)
Laatst gelogd: 22:51:53

Error _async_update_data: 'Timeout' object does not support the context manager protocol

**Comment by MarcoGos** [comment]
Hi @EDelsman, I checked this on 2024.11.0b1 but don't get this error. Also removed and reinstalled the integration, but still working fine. Can you try to remove and reinstall the integration to see if that helps?

**Comment by sshaikh** [comment]
For a data point, I'm getting this error in `2024.10.4`. I'll assume it'll go away in `2024.11`
