### ISSUE TITLE
Intergration does not work anymore

### ISSUE THREAD

**Issue by nagelkemg** [MarcoGos/kleenex_pollenradar#15]
This morning after i installed 2024.12.2 this intergration does noet work anymore, please help?

**Comment by MarcoGos** [comment]
@nagelkemg I just installed 2024.12.2 myself with no issues, therefor you need to provide more information. Take a look at the log to see if any errors occurred.

**Comment by nagelkemg** [comment]
I looked in The log and saw a scrape, i removed that from The config and The it worked again. Thanks for The help.
