### ISSUE TITLE
Request to add the detailed sensors to the main 3 provided to the integration

### ISSUE THREAD

**Issue by thx1e** [MarcoGos/kleenex_pollenradar#3]
Currently, the integration provides three main sensors that display the total count for each type of pollen. However, I find that having more specific information about each type of pollen would greatly enhance the usefulness of the integration for me and other users.

I have been using the scrape function in Home Assistant to fetch additional sensors that provide details on each type of pollen. This allows me to monitor and track pollen levels more effectively.

I would like to request that the integration be updated to include these detailed sensors. The scrape function has been working well but I think it would be better to have all the sensors available within the integration itself, rather than relying on external configuration.

Here is an example of the configuration from [Help request Pollen sensor Dutch hooikoortsradar.nl](https://community.home-assistant.io/t/help-request-pollen-sensor-dutch-hooikoortsradar-nl/524633/11) I am currently using with the scrape function to fetch the additional sensors:

`
#scrape
scrape:
  - resource: https://www.kleenex.nl/api/sitecore/Pollen/GetPollenContentCity?city=POSTCODE

    method: POST
`#    payload: "city=YOUR CITYNAME OR POSTAL CODE"
    headers:
      User-Agent: Home Assistant
      Content-Type: application/x-www-form-urlencoded; charset=UTF-8
    scan_interval: 3600
`
  sensor:

      - name: Pollen (gras)
        select: "li.day-container:nth-child(1) > button"
        attribute: "data-grass-count"
        unique_id: pollen_gras
        unit_of_measurement: ppm
        value_template: >-
          {{ value.split(" ")[0] }}

      - name: Pollen (Poaceae)
        select: "li.day-container:nth-child(1) > button"
        attribute: "data-grass-detail"
        unique_id: pollen_poaceae
        unit_of_measurement: ppm
        value_template: >-
          {{ value.split(",")[1] }}

      - name: Pollen (kruiden)
        select: "li.day-container:nth-child(1) > button"
        attribute: "data-weeds-count"
        unique_id: pollen_kruiden
        unit_of_measurement: ppm
        value_template: >-
          {{ value.split(" ")[0] }}

      - name: Pollen (Bijvoet)
        select: "li.day-container:nth-child(1) > button"
        attribute: "data-weed-detail"
        unique_id: pollen_bijvoet
        unit_of_measurement: ppm
        value_template: >-
          {{ value.split(",")[1] }}

      - name: Pollen (Ganzevoet)
        select: "li.day-container:nth-child(1) > button"
        attribute: "data-weed-detail"
        unique_id: pollen_ganzevoet
        unit_of_measurement: ppm
        value_template: >-
          {{ value.split(",")[3] }}

      - name: Pollen (Ambrosia)
        select: "li.day-container:nth-child(1) > button"
        attribute: "data-weed-detail"
        unique_id: pollen_ambrosia
        unit_of_measurement: ppm
        value_template: >-
          {{ value.split(",")[5] }}

      - name: Pollen (Brandnetel)
        select: "li.day-container:nth-child(1) > button"
        attribute: "data-weed-detail"
        unique_id: pollen_brandnetel
        unit_of_measurement: ppm
        value_template: >-
          {{ value.split(",")[7] }}

      - name: Pollen (bomen)
        select: "li.day-container:nth-child(1) > button"
        attribute: "data-trees-count"
        unique_id: pollen_bomen
        unit_of_measurement: ppm
        value_template: >-
          {{ value.split(" ")[0] }}

      - name: Pollen (Hazelaar)
        select: "li.day-container:nth-child(1) > button"
        attribute: "data-tree-detail"
        unique_id: pollen_hazelaar
        unit_of_measurement: ppm
        value_template: >-
          {{ value.split(",")[1] }}

      - name: Pollen (Iep)
        select: "li.day-container:nth-child(1) > button"
        attribute: "data-tree-detail"
        unique_id: pollen_iep
        unit_of_measurement: ppm
        value_template: >-
          {{ value.split(",")[3] }}

      - name: Pollen (Pijnboom)
        select: "li.day-container:nth-child(1) > button"
        attribute: "data-tree-detail"
        unique_id: pollen_pijnboom
        unit_of_measurement: ppm
        value_template: >-
          {{ value.split(",")[5] }}

      - name: Pollen (Els)
        select: "li.day-container:nth-child(1) > button"
        attribute: "data-tree-detail"
        unique_id: pollen_els
        unit_of_measurement: ppm
        value_template: >-
          {{ value.split(",")[7] }}

      - name: Pollen (Populier)
        select: "li.day-container:nth-child(1) > button"
        attribute: "data-tree-detail"
        unique_id: pollen_populier
        unit_of_measurement: ppm
        value_template: >-
          {{ value.split(",")[9] }}

      - name: Pollen (Eik)
        select: "li.day-container:nth-child(1) > button"
        attribute: "data-tree-detail"
        unique_id: pollen_eik
        unit_of_measurement: ppm
        value_template: >-
          {{ value.split(",")[11] }}

      - name: Pollen (Plataan)
        select: "li.day-container:nth-child(1) > button"
        attribute: "data-tree-detail"
        unique_id: pollen_plataan
        unit_of_measurement: ppm
        value_template: >-
          {{ value.split(",")[13] }}

      - name: Pollen (Berk)
        select: "li.day-container:nth-child(1) > button"
        attribute: "data-tree-detail"
        unique_id: pollen_berk
        unit_of_measurement: ppm
        value_template: >-
          {{ value.split(",")[15] }}

      - name: Pollen (Cipres)
        select: "li.day-container:nth-child(1) > button"
        attribute: "data-tree-detail"
        unique_id: pollen_cipres
        unit_of_measurement: ppm
        value_template: >-
          {{ value.split(",")[17] }}
`
Thanks.

**Comment by MarcoGos** [comment]
Please take a look at the details-attribute of every sensor. You will see there the information you are looking for.
