### ISSUE TITLE
no statistics for entities

### ISSUE THREAD

**Issue by Rvh91** [MarcoGos/kleenex_pollenradar#5]
Thank you for adding this integration! was previously getting this with the scrape integration, but this is much cleaner.

The pollen entities are not generating statistics. This can be resolved by setting state_class: measurement 

further configuration of the entities can also be done by setting: 
device_class: pm10
since pollen can be classified as pm10 

as a side note, do you have a card or automation that uses the forecast already? would be interesting to see how you have implemented a use for the forecast!

**Comment by MarcoGos** [comment]
Hi @Rvh91, I'm working on a new version with added statistics. Also looked at the device_class pm10, but that uses "ug/m3" as unit of measure and that doesn't match the ppm.

Someone in another issue added a nice dashboard setup example for forecast, see: https://github.com/MarcoGos/kleenex_pollenradar/issues/2

**Comment by Rvh91** [comment]
You are right, that unit doesn't fit here. I guess there is no way to specify both? Awesome dashboard setup you linked! thanks!

**Comment by MarcoGos** [comment]
Statistics added by release 1.0.0
