### ISSUE TITLE
Grass and  Weed are missing

### ISSUE THREAD

**Issue by Gazzzman61** [MarcoGos/kleenex_pollenradar#6]
Entities missing,
Only Tree is working, Grass and weed gives "0" and is not updated.

**Comment by MarcoGos** [comment]
Hi, where do you live? If it's the northern hemisphere is't normal in spring to only have tree pollen and no grass and weeds. They will appear later in the year. Did you check the pollen radar on the kleenex website of your country to see if grass pollen are already active?

**Comment by Gazzzman61** [comment]
Thank for your quick response, I live in the Netherlands. Never realised that the grass and weeds are only active in the season of spring and summer. On the Kleenex website is says "0" but not that it is not active.
I close the issue.
