### ISSUE TITLE
Position isn't within chosen region

### ISSUE THREAD

**Issue by axeman91** [MarcoGos/kleenex_pollenradar#8]
I have tried to configure this integration using my home zone latitude and longitude and setting the region to United Kingdom, but when clicking submit I receive the error "Looks like you position isn't within the choosen region".

Testing using the details in the screenshot allow the config to be submitted correctly.

**Comment by MarcoGos** [comment]
Hi @axeman91 , can you tell me your village, town or city you live in?

**Comment by axeman91** [comment]
Hi @MarcoGos , I live close to Porstmouth in the UK

**Comment by MarcoGos** [comment]
@axeman91 When I use the following gps coordinates: latitude: 50.79899 longitude: -1.09125, I don't have any problems and can add the integration without errors.
<img width="381" alt="Scherm­afbeelding 2024-06-25 om 13 28 51" src="https://github.com/MarcoGos/kleenex_pollenradar/assets/44016861/e30fa99c-ae0f-40e4-9663-8f12b61654f7">

**Comment by axeman91** [comment]
@MarcoGos - I just tried the settings in your screenshot and still get the same error when I click submit.  I also noticed that there was an update available and installed that, and it went through fine, so maybe something in the update?

The correct laitude and longitude for my exact location still don't work though, what does this get validated against?

**Comment by MarcoGos** [comment]
@axeman91 It does a POST on url "https://www.kleenex.co.uk/api/sitecore/Pollen/GetPollenContent" with json data: {"lat": <latitude>, "lng": <longitude>}
